image: node:12-alpine

before_script:
  - echo "Initialize the gitlab ci environment";
  - which ssh-agent || ( apk update && apk add --no-cache openssh-client )
  - eval $(ssh-agent -s)
  - echo "$PROD_SSH_PRI_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -m 700 -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - >
    if [ $CI_COMMIT_REF_NAME == "master" ]; then
      USER=$PROD_SERVER_USER;
      SERVER=$PROD_SERVER_IP;
    fi
  - echo "End";

stages:
  - deploy

deploy_source_code:
  stage: deploy
  script:
    - echo "Deploy to server..."
    - >
      if [ $CI_COMMIT_REF_NAME == "master" ]; then
        ssh -p 2222 $USER@$SERVER "
          cd /root/torii_webui;
          git pull;
          docker-compose down --rmi all;
          docker-compose up -d;
          docker push registry.gitlab.com/meshub/torii_webui/transcoder-api:2.3
          "
      fi
    - echo "Success deploymemnt~";
  only:
    - master
    - merge_request
