version: "3.3"
services: 
  transcoder-api:
    image: registry.gitlab.com/meshub/torii_webui/transcoder-api:2.2
    build: .
    restart: always
    ports:
      - 21543:21543
    container_name: 'transcoder-api'
    env_file: ./.env
    volumes:
      - result-mp4:${PWD}/api/public/result
      - split-mp4:${PWD}/api/public/upload
volumes:
  result-mp4:
  split-mp4:
