version: "3.3"
services: 
  transcoder-api:
    image: registry.gitlab.com/meshub/torii_webui/transcoder-api:2.0
    build: .
    restart: always
    ports:
      - 21543:21543
    container_name: 'transcoder-api'
