version: "3.3"
services: 
  meshub-server:
    build: .
    restart: always
    ports:
      - 21543:21543
    container_name: 'meshub-server'
    depends_on:
      - mongodb-server
  mongodb-server:
    build: ../mongodb-docker
    restart: always
    ports:
      - 27017:27017
    container_name: 'meshub-mongo'
    volumes:
      - ../mongodb-docker/db:/data/db
