version: "3.3"
services: 
  meshub-server:
    build: .
    restart: always
    ports:
      - 21543:21543
    container_name: 'transcoder-api'
    volumes:
      - /var/www/torii-demo.meshub.io/v2/result:/var/www/torii-demo.meshub.io/v2/result
      - /var/www/torii-demo.meshub.io/v2/upload:/var/www/torii-demo.meshub.io/v2/upload
